[package]
name = "prov-history"
readme.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
description = "History bounded context for prov workspaces"

[dependencies]
prov-graph = { path = "../prov-graph", version = "0.4.0", default-features = false }
prov-transaction = { path = "../prov-transaction", version = "0.4.0", default-features = false }
prov-fixity = { path = "../prov-fixity", version = "0.4.0" }
prov-config = { path = "../prov-config", version = "0.4.0", default-features = false }
fig.workspace = true

[features]
default = ["yaml"]
yaml = [
    "fig/yaml",
    "prov-graph/yaml",
    "prov-config/yaml",
    "prov-transaction/yaml",
]
json = [
    "fig/json",
    "prov-graph/json",
    "prov-config/json",
    "prov-transaction/json",
]
toml = [
    "fig/toml",
    "prov-graph/toml",
    "prov-config/toml",
    "prov-transaction/toml",
]
fig-lang = [
    "fig/fig",
    "prov-graph/fig-lang",
    "prov-config/fig-lang",
    "prov-transaction/fig-lang",
]
